//! Execution Engine Type Definitions

use crate::agentic::core::Message;
use crate::agentic::round_preempt::{
    DialogRoundPreemptSource, DialogRoundSteeringInterrupt, DialogRoundSteeringSource,
};
use crate::agentic::tools::pipeline::SubagentParentInfo;
use crate::agentic::tools::ToolRuntimeRestrictions;
use crate::agentic::workspace::WorkspaceServices;
use crate::agentic::WorkspaceBinding;
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Execution context
#[derive(Clone)]
pub struct ExecutionContext {
    pub session_id: String,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub agent_type: String,
    pub workspace: Option<WorkspaceBinding>,
    pub context: HashMap<String, String>,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub skip_tool_confirmation: bool,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    /// Workspace I/O services (filesystem + shell) injected into tools
    pub workspace_services: Option<WorkspaceServices>,
    /// When set, engine may end the turn after a full model round if a user message was queued.
    pub round_preempt: Option<Arc<dyn DialogRoundPreemptSource>>,
    /// When set, engine drains pending user steering messages at each round boundary
    /// and injects them into the dialog history without ending the turn.
    pub round_steering: Option<Arc<dyn DialogRoundSteeringSource>>,
    /// When true, stream cancellation may be converted into a partial assistant
    /// result if text/tool output has already been produced.
    pub recover_partial_on_cancel: bool,
}

/// Round context
#[derive(Debug, Clone)]
pub struct RoundContext {
    pub session_id: String,
    pub subagent_parent_info: Option<SubagentParentInfo>,
    pub dialog_turn_id: String,
    pub turn_index: usize,
    pub round_number: usize,
    pub workspace: Option<WorkspaceBinding>,
    pub messages: Vec<Message>,
    pub available_tools: Vec<String>,
    pub model_name: String,
    pub agent_type: String,
    pub context_vars: HashMap<String, String>,
    pub runtime_tool_restrictions: ToolRuntimeRestrictions,
    /// Cooperative interrupt checked by tool execution so user steering can be
    /// applied after the currently running atomic tool/batch finishes.
    pub steering_interrupt: Option<DialogRoundSteeringInterrupt>,
    pub cancellation_token: CancellationToken,
    pub workspace_services: Option<WorkspaceServices>,
    pub recover_partial_on_cancel: bool,
}

/// Round result
#[derive(Debug, Clone)]
pub struct RoundResult {
    pub assistant_message: Message,
    pub tool_calls: Vec<crate::agentic::core::ToolCall>,
    pub tool_result_messages: Vec<Message>,
    pub has_more_rounds: bool,
    pub finish_reason: FinishReason,
    /// Token usage statistics (from model response)
    pub usage: Option<crate::util::types::ai::GeminiUsage>,
    /// Provider-specific metadata returned by the model.
    pub provider_metadata: Option<Value>,
    /// When set, this round's stream was partially recovered (aborted mid-way
    /// but some output was already received). Contains a human-readable reason.
    pub partial_recovery_reason: Option<String>,
    /// True when the model emitted any non-empty assistant text in this round.
    /// Used by the execution engine to distinguish "model gave a final answer"
    /// (text-only round, end the turn) from "model stalled with thinking-only"
    /// (no text, no tool_call — needs rescue).
    pub had_assistant_text: bool,
    /// True when the model emitted any non-empty thinking / reasoning content
    /// in this round.
    pub had_thinking_content: bool,
}

/// Finish reason
#[derive(Debug, Clone, PartialEq)]
pub enum FinishReason {
    /// Normal completion
    Complete,
    /// Need to execute tools
    ToolCalls,
    /// User cancelled
    Cancelled,
    /// Error
    Error,
}

impl std::fmt::Display for FinishReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FinishReason::Complete => write!(f, "complete"),
            FinishReason::ToolCalls => write!(f, "tool_calls"),
            FinishReason::Cancelled => write!(f, "cancelled"),
            FinishReason::Error => write!(f, "error"),
        }
    }
}

/// Execution result
#[derive(Debug, Clone)]
pub struct ExecutionResult {
    /// Last assistant message
    pub final_message: Message,
    pub total_rounds: usize,
    pub success: bool,
    /// All new messages generated by this execution (including AI responses and tool results)
    pub new_messages: Vec<Message>,
    /// Why the execution finished
    pub finish_reason: FinishReason,
}
