use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    if let Err(e) = embed_cli_prompts() {
        eprintln!("Warning: Failed to embed CLI prompts: {}", e);
    }
}

fn embed_cli_prompts() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let prompts_dir = Path::new(&manifest_dir).join("prompts");

    println!("cargo:rerun-if-changed=prompts");

    let mut prompts = HashMap::new();

    if prompts_dir.exists() {
        read_prompt_files(&prompts_dir, &prompts_dir, &mut prompts)?;
    }

    generate_prompts_code(&prompts)?;

    println!("Embedded {} CLI prompt(s)", prompts.len());
    Ok(())
}

fn read_prompt_files(
    current_dir: &Path,
    base_dir: &Path,
    prompts: &mut HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(current_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            read_prompt_files(&path, base_dir, prompts)?;
        } else if matches!(path.extension().and_then(|e| e.to_str()), Some("md" | "txt")) {
            let content = fs::read_to_string(&path)?;
            let relative = path
                .strip_prefix(base_dir)?
                .to_string_lossy()
                .replace('\\', "/");
            // Key: filename without extension, e.g. "init" from "init.md"
            let key = relative
                .trim_end_matches(".md")
                .trim_end_matches(".txt")
                .to_string();
            prompts.insert(key, content);
        }
    }
    Ok(())
}

fn generate_prompts_code(
    prompts: &HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("embedded_cli_prompts.rs");
    let mut f = fs::File::create(&dest)?;

    writeln!(f, "// Auto-generated by build.rs — do not edit")?;
    writeln!(f)?;
    writeln!(f, "use std::collections::HashMap;")?;
    writeln!(f, "use once_cell::sync::Lazy;")?;
    writeln!(f)?;
    writeln!(f, "pub static CLI_PROMPTS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {{")?;
    writeln!(f, "    let mut m = HashMap::new();")?;

    for (key, content) in prompts {
        writeln!(f, "    m.insert(r###\"{}\"###, r###\"{}\"###);", key, content)?;
    }

    writeln!(f, "    m")?;
    writeln!(f, "}});")?;
    writeln!(f)?;

    writeln!(f, "/// Get an embedded CLI prompt by name")?;
    writeln!(f, "pub fn get_cli_prompt(name: &str) -> Option<&'static str> {{")?;
    writeln!(f, "    CLI_PROMPTS.get(name).copied()")?;
    writeln!(f, "}}")?;

    Ok(())
}
